name: NUnit Test Database

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    services:
      mysql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          # The MySQL docker container requires these environment variables to be set
          # so we can create and migrate the test database.
          # See: https://hub.docker.com/_/mysql
          MYSQL_DATABASE: library
          MSSQL_SA_PASSWORD: mysql_test
          ACCEPT_EULA: Y
        ports:
          - 1433:1433
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        host port: 3308 # Optional, default value is 3306. The port of host
        container port: 3308 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'mysql_test' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'mysql_test' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'mysql_test' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: mysql_test # Required if "mysql user" exists. The password for the "mysql user"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    # - name: Setup .NET
    - name: Restore Dependencies
      run: dotnet restore EasyEfDb/EasyEfDb.csproj

    # - name: Setup .NET
    - name: Restore Dependencies
      run: dotnet restore EasyEfDb.Tests/EasyEfDb.Tests.csproj

    - name: Build
      run: dotnet build EasyEfDb/EasyEfDb.csproj --configuration Release --runtime linux-x64

    - name: Build
      run: dotnet build  EasyEfDb.Tests/EasyEfDb.Tests.csproj --configuration Release --runtime linux-x64

    - name: Test
      run: dotnet test --environment ASPNETCORE_ENVIRONMENT_DB_TEST=Mssql